---
# tasks file for ansible-role-ruby
- name: Install the dependencies
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - centos-release-scl
  when: ansible_distribution == 'CentOS'

- name: Enable rhel-server-rhcscl-7-rpms repository
  shell: yum-config-manager --enable rhel-server-rhscl-7-rpms
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Show ruby_version
  debug:
    msg: "{{ ruby_version }}"
    verbosity: 3

- name: install rh-ruby22
  yum:
    name: rh-ruby22
  when: ruby_version == 2.2

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby22.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.2

- name: install rh-ruby23
  yum:
    name: rh-ruby23
  when: ruby_version == 2.3

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby23.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.3

- name: install rh-ruby24
  yum:
    name: rh-ruby24
  when: ruby_version == 2.4

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby24.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.4
