---
sudo: required
language: python
services:
  - docker
env:

install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule test
  - molecule --debug test --scenario-name=postgres

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
