---
# TODO SELinux policies
# TCP Socket with systemd
- name: Install the required dependencies
  yum: 
    state: installed 
    name: "{{ item }}"
  with_items:
   - mariadb-server
   - ruby-devel
   - ImageMagick-devel
   - gcc
   - patch
   - mariadb-devel
   - MySQL-python
   - epel-release

- name: Install Nginx
  yum: 
      state: installed 
      name: nginx
  when: redmine_configure_nginx

- name: Enable MariaDB server
  service: 
      name: mariadb 
      state: started 
      enabled: yes

- name: Enable Nginx server
  service: 
      name: nginx 
      state: started 
      enabled: yes
  when: redmine_configure_nginx

- name: Create redmine DB
  mysql_db:
    name={{ redmine_sql_database_name }} state=present

- name: Create redmine DB user
  mysql_user:
    name={{ redmine_sql_username}}
    password={{ redmine_sql_password }}
    host={{ redmine_sql_database_host }}
    priv={{ redmine_sql_database_name }}.*:ALL
    state=present

- name: Create the Redmine user
  user: 
      name: redmine

- name: Check redmine catalog
  stat: path={{ redmine_home }}
  register: redmine_cat

- name: Download Redmine
  get_url:
    url=http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz
    dest=/home/redmine/
  become: yes
  become_user: redmine
  when: redmine_cat.stat.exists == False

- name: Unpack Redmine source tarball
  unarchive:
    src: /home/redmine/redmine-{{ redmine_version }}.tar.gz
    dest: /home/redmine/
    copy: no
  become: yes
  become_user: redmine
  when: redmine_cat.stat.exists == False

- name: Install the required gems - bundler
  gem: 
      name: bundler 
      state: present 
      user_install: yes
      version: 1.15.4
  become: yes
  become_user: redmine

# - name: Install bundler via gem
#   shell: /bin/gem install bundler
#   become: yes
#   become_user: redmine
#   args:
#     chdir: /home/redmine/

#   # Bundler is available in Ansible 2.0
# - name: Install the required gems via bundler - rmagick
#   become: yes
#   become_user: redmine
#   shell: /home/redmine/bin/bundler install --without development test rmagick
#   args:
#     chdir: "{{ redmine_home }}"
 
- name: Upload the Redmine configuration file
  template: 
     src: database.yml 
     dest: "{{ redmine_home }}/config/"
  become: yes
  become_user: redmine

- name: Install the required gems via bundler 
  become: yes
  become_user: redmine
  shell: /home/redmine/bin/bundler install 
  args:
    chdir: "{{ redmine_home }}"
 
- name: Generate secret token
  become: yes
  become_user: redmine
  shell: /home/redmine/bin/bundle exec /home/redmine/bin/rake generate_secret_token
  args:
    chdir: "{{ redmine_home }}"

- name: DB Migrate
  shell: RAILS_ENV=production /home/redmine/bin/bundle  exec /home/redmine/bin/rake db:migrate
  become: yes
  become_user: redmine
  args:
    chdir: "{{ redmine_home }}"

- name: Local gemfile
  template: 
   src: Gemfile.local
   dest: "{{ redmine_home }}"

- name: Install the required gems via bundler  - unicorn
  become: yes
  become_user: redmine
  shell: /home/redmine/bin/bundler install 
  args:
    chdir: "{{ redmine_home }}"

- name: Create directories for shared resources
  file:
   path: "{{ redmine_home }}/shared/{{ item }}"
   state: directory
  with_items:
   - config/redmine
   - log/redmine
   - pid/redmine
   - socket/redmine
  become: yes
  become_user: redmine

- name: unicorn.conf.rb file
  template:
      src: unicorn.conf.rb
      dest: "{{ redmine_home }}/shared/config/redmine/"
  become: yes
  become_user: redmine

- name: run directory
  file:
      path: /var/run/redmine
      state: directory
      owner: redmine
      group: redmine

- name: Redmine start and stop scripts
  template: 
    src: "{{ item }}"
    dest: /home/redmine/bin/
    mode: u+x
  with_items:
    - stop-redmine-unicorn
    - start-redmine-unicorn
  become: yes
  become_user: redmine

- name: Systemd script
  template:
      src: usr/lib/systemd/system/redmine.service
      dest: /usr/lib/systemd/system/

- name: Default data
  shell: RAILS_ENV=production REDMINE_LANG=en /home/redmine/bin/bundle exec /home/redmine/bin/rake redmine:load_default_data
  become: yes
  become_user: redmine
  args:
    chdir: "{{ redmine_home }}"

- name: temp dir
  file: 
    path: "{{ redmine_home }}/{{ item }}" 
    state: directory
    owner: redmine
    group: redmine
    mode: 0755
  with_items:
   - "tmp/pdf"
   - "public/plugin_assets"
   - "files"
   - "log"

- name: Open http port
  firewalld: 
      port: "80/tcp"
      permanent: true 
      state: enabled
  notify:
   - Firewalld restart
  when: redmine_configure_firewalld

- name: Permissions for Nginx to read Redmine files
  file:
    path: "{{ item }}"
    recurse: yes
    mode: o+rx
  with_items:
    - /home/redmine
    - /var/run/redmine
  when: redmine_configure_nginx

- name: Nginx configuration 
  template:
    src: redmine.conf
    dest: /etc/nginx/conf.d/
  notify:
   - Nginx reload
  when: redmine_configure_nginx

- name: Enable redmine systemd unit
  service: 
    name: redmine
    state: started
    enabled: yes
