---
- name: Allow Nginx to access the Unicorn ports
  seport:
    ports: "{{ redmine_unicorn_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Relabel SELinux context
  file:
    path: "{{ redmine_runtime_directory }}/public"
    setype: httpd_sys_content_t
    recurse: true
  when: redmine_configure_selinux
