---
# handlers file for ansible-role-redmine/
- name: Firewalld reload
  service:
      name: firewalld
      state: reloaded

- name: Firewalld restart
  service:
      name: firewalld
      state: restarted

- name: Nginx reload
  service:
      name: nginx
      state: reloaded

- name: redmine restart
  service:
      name: redmine
      state: restarted
