---
- name: Converge
  hosts: all
  roles:
    - bngsudheer.ruby
    
- name: Converge
  hosts: all
  pre_tasks:
    # fails because of https://github.com/ansible/ansible/issues/27520
    - name: Reset connection
      meta: reset_connection
  roles:
    - ansible-role-redmine
