---
- name: Converge
  hosts: all
  roles:
    - bngsudheer.ruby
    
- name: Converge
  hosts: all
  # pre_tasks:
  #   - name: Reset connection
  #     meta: reset_connection
  roles:
    - ansible-role-redmine
