---
# If Ruby is required. Perhaps move this to a diffeerent scenario
# - name: Converge
#   hosts: all
#   roles:
#     - bngsudheer.ruby

- name: Converge
  hosts: all
  vars:
    # pre_tasks:
    # fails because of https://github.com/ansible/ansible/issues/27520
    # - name: Reset connection
    #   meta: reset_connection
    - centos_base_enable_epel: true
    - centos_base_fail2ban_configuration: true
    - centos_base_install_selinux_packages: true
    - centos_base_basic_packages: true
    - redmine_sql_database_name: "redmine"
    - redmine_sql_database_host: "localhost"
    - redmine_sql_username: "redmine"
    - redmine_sql_password: "password"
    - redmine_unicorn_port: 5777
    - redmine_configure_selinux: false
    - redmine_plugins:
        - name: scrum
          base_name: scrum
          url: https://redmine.ociotec.com/attachments/download/481/scrum-v0.18.1.tar.gz
        - name: timesheet
          base_name: timesheet
          url: https://github.com/Contargo/redmine-timesheet-plugin/archive/master.zip
    - mysql_databases:
        - name: redmine
    - mysql_users:
        - name: redmine
          password: password
          priv: "redmine.*:ALL"
  pre_tasks:
    - name:
      yum:
        name: '{{ item }}'
      with_items:
        - zlib-static
        # - zlib-ada-devel
        # - zlib-ada
  roles:
    - geerlingguy.mysql
    - bngsudheer.centos_base
    - ansible-role-redmine
